version: '3.8'

services:
  python-tester:
    image: python:3.11-slim
    container_name: python-tester
    command: ["python", "/app/run_tests.py"]
    volumes:
      - ./app:/app:ro  # Read-only mount
    networks:
      - internal
    user: "1000:1000"  # Non-root user
    read_only: true
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID

  frontend:
    image: node:20-alpine
    container_name: frontend
    working_dir: /app
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app:ro
    ports:
      - "8080:8080"
    networks:
      - internal
    user: "1000:1000"
    read_only: true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

networks:
  internal:
    driver: bridge